# Generated by Django 4.0.5 on 2023-04-09 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("venues", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.FloatField()),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="venues.event")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("seat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="venues.seat")),
            ],
            options={
                "unique_together": {("seat", "event")},
            },
        ),
    ]
